# Generated by Django 6.0.3 on 2026-03-23 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('competitor_type', models.CharField(choices=[('team', 'Team'), ('athlete', 'Athlete')], default='team', max_length=20)),
                ('_sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitors', to='events.sport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_indoor', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['country', 'city', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'city', 'country'), name='unique_venue_per_city_country')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='scheduled', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('round_label', models.CharField(blank=True, max_length=100)),
                ('_sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.sport')),
                ('_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue')),
            ],
            options={
                'ordering': ['start_datetime', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('participant', 'Participant')], default='participant', max_length=20)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('_competitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_participations', to='events.competitor')),
                ('_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='events.event')),
            ],
            options={
                'ordering': ['_event', 'display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('_event', '_competitor'), name='unique_competitor_per_event')],
            },
        ),
        migrations.AddConstraint(
            model_name='competitor',
            constraint=models.UniqueConstraint(fields=('name', '_sport'), name='unique_competitor_per_sport'),
        ),
    ]
